version: '3.3'

services:
  app:
    image: node:16-alpine3.11
    command: sh -c "npm install && npm run start"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /usr/src/app

  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    ports:
      - ${NGROK_PORT:-4040}:4040
    environment:
      NGROK_PORT: app:3000